[workspace]
members = [
	"runtime/",
	"pallets/parachain-info",
	"pallets/token-dealer",
	"node/",
]
exclude = ["vendor"]

[profile.release]
panic = 'unwind'

[patch.crates-io]
ethereum = { path = "vendor/ethereum" }