name: Publish draft release

on: ["push"]
  push:
    tags:
      - v**.**.**

jobs:
  build-runtimes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Cache Rust dependencies
      uses: actions/cache@v1.1.2
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-
    - uses: actions-rs/toolchain@v1
      with:
        target: wasm32-unknown-unknown
        toolchain: nightly
        default: true
    - name: Build
      run: cargo build --release --verbose --all
    - name: Upload moonbase-testnet node
      uses: actions/upload-artifact@v2
      with:
        name: moonbase-testnet
        path: "target/release/moonbase-testnet"
    - name: Setup environment
      run: source tools/aliases.sh
    - name: Generate parachain specs
      run: parachain_specs
    - name: Upload parachain spec
      uses: actions/upload-artifact@v2
      with:
        name: parachain-specs.json
        path: "specs/moonbase-testnet-parachain-spec-plain.json"
    - name: Generate moonbase-testnet runtime
      run: target/release/moonbase-testnet export-genesis-wasm --chain specs/moonbase-testnet-parachain-spec-plain.json > specs/parachain.wasm
    - name: Upload moonbase-testnet runtime
      uses: actions/upload-artifact@v2
      with:
        name: moonbase-testnet-runtime
        path: "specs/parachain.wasm"
