name: Publish draft release

on: ["push"]

jobs:
  build-runtimes:
    runs-on: ubuntu-latest
    env:
      # PARACHAIN_BINARY: target/release/moonbase-testnet
      PARACHAIN_BINARY: echo
      PARACHAIN_SPEC_TEMPLATE: specs/moonbase-testnet-parachain-spec-template.json
      PARACHAIN_SPEC_PLAIN: specs/moonbase-testnet-parachain-spec-plain.json
      PARACHAIN_SPEC_RAW: specs/moonbase-testnet-parachain-spec-raw.json
    steps:
    # - uses: actions/checkout@v2
    # - name: Submodules
    #   run: git submodule update --init --recursive
    # - name: Cache Rust dependencies
    #   uses: actions/cache@v1.1.2
    #   with:
    #     path: target
    #     key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
    #     restore-keys: |
    #       ${{ runner.OS }}-build-
    # - uses: actions-rs/toolchain@v1
    #   with:
    #     target: wasm32-unknown-unknown
    #     toolchain: nightly
    #     default: true
    # - name: Build
    #   run: cargo build --release --verbose --all
    # - name: Upload moonbase-testnet node
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: moonbase-testnet
    #     path: $PARACHAIN_BINARY
    - name: Generate parachain specs
      run: $PARACHAIN_BINARY build-spec --disable-default-bootnode  | grep '"code"' > /tmp/parachain-tmp-specs.json
    - name: Merging parachain spec template
      run: sed -e '/"<runtime_code>"/{r /tmp/parachain.wasm' -e 'd}'  $PARACHAIN_SPEC_TEMPLATE > $PARACHAIN_SPEC_PLAIN
    - name: Generate parachain raw
      run: $PARACHAIN_BINARY build-spec --disable-default-bootnode --raw --chain $PARACHAIN_SPEC_PLAIN > $PARACHAIN_SPEC_RAW
    - name: Upload parachain plain specs
      uses: actions/upload-artifact@v2
      with:
        name: parachain-specs-$GITHUB_SHA_SHORT-plain.json
        path: "specs/moonbase-testnet-parachain-spec-plain.json"
    - name: Upload parachain raw specs
      uses: actions/upload-artifact@v2
      with:
        name: parachain-specs-$GITHUB_SHA_SHORT-raw.json
        path: "specs/moonbase-testnet-parachain-spec-raw.json"